variable "name" {}
variable "resource_group_name" {}
variable "location" {}
variable "sql_version" {}
variable "administrator_login" {}
variable "administrator_login_password" {}
variable "minimum_tls_version" {}
variable "login_username" {}
variable "object_id" {}
variable "tags" {}
variable "network_rule_count" {}
variable "rule_name" {}
variable "server_id" {}
variable "rule_subnet" {}
variable "ignore_missing_vnet_service_endpoint" {}